
IMAGES_FOLDER = "images"
METADATA_FOLDER = "metadata"
INSPEXP_FILE_NAME = "inspexp.json"
TRAIN_TEST_SPLIT_FILE_NAME = "segm_train_test_split.json"
TRAIN_PATIENTS_KEY = "train_patients"
TEST_PATIENTS_KEY = "test_patients"
PATIENT_ANNOTATIONS_FILE_NAME = "rijnstate.json"
BB_ANNOTATIONS_FILE = "annotations.json"
BB_ANNOTATIONS_EXPANDED_FILE = "annotations_expanded.json"
ANNOTATIONS_TYPE_FILE = "annotations_type.json"
SEPARATOR = "_"